name: Django

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This is a build step"

  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This is a test step"

  integration:
    needs: test
    runs-on: ubuntu-22.04
    continue-on-error: true
    steps:
      - run: echo "This is an integration step"
      - run: exit 1

  prod:
    needs: integration
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - run: echo "This is a deploy step"

  artifact:
    needs: integration
    runs-on: ubuntu-22.04
    steps:
      - run: echo "hello" > hello.txt
      - uses: actions/upload-artifact@v3
        with:
          name: hello-artifact
          path: hello.txt
